export const drivers = [
  {
    Id: 1,
    name: "Ali Elchab",
    email: "alielchab01@gmail.com",
    location: "Beirut,Lebanon,Haret Hreik",
    car: "Toyota",
    color: "grey",
    plateNumber: "6F8E24",
    password: "123456",
    status: "Active",
  },
  {
    Id: 2,
    name: "Ali Elchab",
    email: "alielchab01@gmail.com",
    location: "Beirut,Lebanon,Haret Hreik",
    car: "Toyota",
    color: "grey",
    plateNumber: "6F8E24",
  },
  {
    Id: 3,
    name: "Ali Elchab",
    email: "alielchab01@gmail.com",
    location: "Beirut,Lebanon,Haret Hreik",
    car: "Toyota",
    color: "grey",
    plateNumber: "6F8E24",
  },
  {
    Id: 6,
    name: "Ali Elchab",
    email: "alielchab01@gmail.com",
    location: "Beirut,Lebanon,Haret Hreik",
    car: "Toyota",
    color: "grey",
    plateNumber: "6F8E24",
  },
];

export const orders = [
  {
    orderId: 1,
    passenger: "Mhmd",
    picked_up: "beirut",
    drop_off: "Tyre",
    ride_time: "80 mins",
    status: "Finished",
    rating: "5.0",
    date: "20203-12-13",
  },
  {
    orderId: 2,
    passenger: "Mhmd",
    picked_up: "beirut",
    drop_off: "Tyre",
    ride_time: "80 mins",
    status: "Finished",
    rating: "5.0",
    date: "20203-12-13",
  },
  {
    orderId: 3,
    passenger: "Mhmd",
    picked_up: "beirut",
    drop_off: "Tyre",
    ride_time: "80 mins",
    status: "Finished",
    rating: "5.0",
    date: "20203-12-13",
  },
];
